version: '3.8'
services:
  serv1:
    build: ./backend/api_livres
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - mongodb
  serv2:
    build: ./backend/api_emprunt
    ports:
      - 3001:3000
    depends_on:
      - rabbitmq
      - mongodb
  serv3:
    build: ./backend/api_clients
    ports:
      - 3002:3000
    depends_on:
      - rabbitmq
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 8080:80
  gateway:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ management console
  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # MongoDB default port
